// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/NicklasWallgren/go-template/domain/common"

	mock "github.com/stretchr/testify/mock"
)

// EntityDeleteValidator is an autogenerated mock type for the EntityDeleteValidator type
type EntityDeleteValidator[T common.EntityConstraint] struct {
	mock.Mock
}

type EntityDeleteValidator_Expecter[T common.EntityConstraint] struct {
	mock *mock.Mock
}

func (_m *EntityDeleteValidator[T]) EXPECT() *EntityDeleteValidator_Expecter[T] {
	return &EntityDeleteValidator_Expecter[T]{mock: &_m.Mock}
}

// ValidateToDelete provides a mock function with given fields: ctx, entity
func (_m *EntityDeleteValidator[T]) ValidateToDelete(ctx context.Context, entity *T) error {
	ret := _m.Called(ctx, entity)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *T) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EntityDeleteValidator_ValidateToDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToDelete'
type EntityDeleteValidator_ValidateToDelete_Call[T common.EntityConstraint] struct {
	*mock.Call
}

// ValidateToDelete is a helper method to define mock.On call
//  - ctx context.Context
//  - entity *T
func (_e *EntityDeleteValidator_Expecter[T]) ValidateToDelete(ctx interface{}, entity interface{}) *EntityDeleteValidator_ValidateToDelete_Call[T] {
	return &EntityDeleteValidator_ValidateToDelete_Call[T]{Call: _e.mock.On("ValidateToDelete", ctx, entity)}
}

func (_c *EntityDeleteValidator_ValidateToDelete_Call[T]) Run(run func(ctx context.Context, entity *T)) *EntityDeleteValidator_ValidateToDelete_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*T))
	})
	return _c
}

func (_c *EntityDeleteValidator_ValidateToDelete_Call[T]) Return(_a0 error) *EntityDeleteValidator_ValidateToDelete_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewEntityDeleteValidator interface {
	mock.TestingT
	Cleanup(func())
}

// NewEntityDeleteValidator creates a new instance of EntityDeleteValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEntityDeleteValidator[T common.EntityConstraint](t mockConstructorTestingTNewEntityDeleteValidator) *EntityDeleteValidator[T] {
	mock := &EntityDeleteValidator[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
