// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/NicklasWallgren/go-template/domain/common"

	mock "github.com/stretchr/testify/mock"
)

// EntityCreationValidator is an autogenerated mock type for the EntityCreationValidator type
type EntityCreationValidator[T common.EntityConstraint] struct {
	mock.Mock
}

type EntityCreationValidator_Expecter[T common.EntityConstraint] struct {
	mock *mock.Mock
}

func (_m *EntityCreationValidator[T]) EXPECT() *EntityCreationValidator_Expecter[T] {
	return &EntityCreationValidator_Expecter[T]{mock: &_m.Mock}
}

// ValidateToCreate provides a mock function with given fields: ctx, entity
func (_m *EntityCreationValidator[T]) ValidateToCreate(ctx context.Context, entity *T) error {
	ret := _m.Called(ctx, entity)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *T) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EntityCreationValidator_ValidateToCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToCreate'
type EntityCreationValidator_ValidateToCreate_Call[T common.EntityConstraint] struct {
	*mock.Call
}

// ValidateToCreate is a helper method to define mock.On call
//  - ctx context.Context
//  - entity *T
func (_e *EntityCreationValidator_Expecter[T]) ValidateToCreate(ctx interface{}, entity interface{}) *EntityCreationValidator_ValidateToCreate_Call[T] {
	return &EntityCreationValidator_ValidateToCreate_Call[T]{Call: _e.mock.On("ValidateToCreate", ctx, entity)}
}

func (_c *EntityCreationValidator_ValidateToCreate_Call[T]) Run(run func(ctx context.Context, entity *T)) *EntityCreationValidator_ValidateToCreate_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*T))
	})
	return _c
}

func (_c *EntityCreationValidator_ValidateToCreate_Call[T]) Return(_a0 error) *EntityCreationValidator_ValidateToCreate_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewEntityCreationValidator interface {
	mock.TestingT
	Cleanup(func())
}

// NewEntityCreationValidator creates a new instance of EntityCreationValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEntityCreationValidator[T common.EntityConstraint](t mockConstructorTestingTNewEntityCreationValidator) *EntityCreationValidator[T] {
	mock := &EntityCreationValidator[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
