// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ValidationFunc is an autogenerated mock type for the ValidationFunc type
type ValidationFunc[T interface{}] struct {
	mock.Mock
}

type ValidationFunc_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *ValidationFunc[T]) EXPECT() *ValidationFunc_Expecter[T] {
	return &ValidationFunc_Expecter[T]{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, subject
func (_m *ValidationFunc[T]) Execute(ctx context.Context, subject *T) error {
	ret := _m.Called(ctx, subject)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *T) error); ok {
		r0 = rf(ctx, subject)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidationFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ValidationFunc_Execute_Call[T interface{}] struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//  - ctx context.Context
//  - subject *T
func (_e *ValidationFunc_Expecter[T]) Execute(ctx interface{}, subject interface{}) *ValidationFunc_Execute_Call[T] {
	return &ValidationFunc_Execute_Call[T]{Call: _e.mock.On("Execute", ctx, subject)}
}

func (_c *ValidationFunc_Execute_Call[T]) Run(run func(ctx context.Context, subject *T)) *ValidationFunc_Execute_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*T))
	})
	return _c
}

func (_c *ValidationFunc_Execute_Call[T]) Return(_a0 error) *ValidationFunc_Execute_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewValidationFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewValidationFunc creates a new instance of ValidationFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewValidationFunc[T interface{}](t mockConstructorTestingTNewValidationFunc) *ValidationFunc[T] {
	mock := &ValidationFunc[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
