linters:
  disable:
    - golint
    - maligned
    - nolintlint
    - ireturn
    - staticcheck # does not support generics
    - unused # does not support generics
    - stylecheck # does not support generics
    - gosimple # does not support generics
    - wrapcheck
    - exhaustruct
    - godox
    - nonamedreturns
    - exhaustivestruct
    - varnamelen
    - nosprintfhostport
    - gochecknoglobals
    - gci
    - gomnd
    - testpackage
    - gomoddirectives

  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

linters-settings:
  govet:
    disable:
      - fieldalignment

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: true

run:
  go: '1.18'
  skip-dirs:
    - adapters/driver/persistence/transaction


