linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
#    - exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
#    - gci
#    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
#    - godot temporary
#    - godox temporary
    - gofmt
    - gofumpt
    - goheader
    - goimports
#    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - ifshort
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
#    - varnamelen
    - wastedassign
    - whitespace
#    - wrapcheck
    - wsl

  disable:
    - interfacer
    - golint
    - scopelint
    - maligned
    - lll
    - nolintlint
    - ireturn
    - goerr113
    - govet
    - staticcheck
    - gocritic
    - revive
    - unused
    - stylecheck
    - gosimple
    - godot # temporary
    - wrapcheck # temporary
    - exhaustruct
    - godox # temporary
    - nonamedreturns
    - exhaustivestruct
    - varnamelen
    - nosprintfhostport
    - gochecknoglobals
    - gci
    - gomnd

  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused


linters-settings:
  check-shadowing: true
  enable-all: true

  govet:
    enable:
      - fieldalignment

issues:
  exclude-use-default: false

run:
  go: '1.18'
  skip-dirs:
    - adapters/driver/persistence/transaction


