version: '2.3'

networks:
  private:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: ./deployment/docker/Dockerfile
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    networks:
      - private

  mariadb:
    image: library/mariadb:10.5.10
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=go_template
    ports:
      - 3306:3306
    networks:
      - private
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./deployment/docker/mariadb/:/docker-entrypoint-initdb.d/
    entrypoint:
      sh -c "/usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_MULTIPLE_DATABASES=go_template,go_template_test
    ports:
      - 5432:5432
    networks:
      - private
    volumes:
      - ./deployment/docker/postgres/:/docker-entrypoint-initdb.d/

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:3.7.23-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - private
    volumes:
      - rabbitmq_data:/data

volumes:
  rabbitmq_data:
  mariadb_data:
  postgresdb_data: