// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// APIRequest is an autogenerated mock type for the APIRequest type
type APIRequest struct {
	mock.Mock
}

type APIRequest_Expecter struct {
	mock *mock.Mock
}

func (_m *APIRequest) EXPECT() *APIRequest_Expecter {
	return &APIRequest_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewAPIRequest interface {
	mock.TestingT
	Cleanup(func())
}

// NewAPIRequest creates a new instance of APIRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAPIRequest(t mockConstructorTestingTNewAPIRequest) *APIRequest {
	mock := &APIRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
