// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Middleware is an autogenerated mock type for the Middleware type
type Middleware struct {
	mock.Mock
}

type Middleware_Expecter struct {
	mock *mock.Mock
}

func (_m *Middleware) EXPECT() *Middleware_Expecter {
	return &Middleware_Expecter{mock: &_m.Mock}
}

// Setup provides a mock function with given fields:
func (_m *Middleware) Setup() {
	_m.Called()
}

// Middleware_Setup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setup'
type Middleware_Setup_Call struct {
	*mock.Call
}

// Setup is a helper method to define mock.On call
func (_e *Middleware_Expecter) Setup() *Middleware_Setup_Call {
	return &Middleware_Setup_Call{Call: _e.mock.On("Setup")}
}

func (_c *Middleware_Setup_Call) Run(run func()) *Middleware_Setup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Middleware_Setup_Call) Return() *Middleware_Setup_Call {
	_c.Call.Return()
	return _c
}

type mockConstructorTestingTNewMiddleware interface {
	mock.TestingT
	Cleanup(func())
}

// NewMiddleware creates a new instance of Middleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMiddleware(t mockConstructorTestingTNewMiddleware) *Middleware {
	mock := &Middleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
