// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// APIResponse is an autogenerated mock type for the APIResponse type
type APIResponse struct {
	mock.Mock
}

type APIResponse_Expecter struct {
	mock *mock.Mock
}

func (_m *APIResponse) EXPECT() *APIResponse_Expecter {
	return &APIResponse_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewAPIResponse interface {
	mock.TestingT
	Cleanup(func())
}

// NewAPIResponse creates a new instance of APIResponse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAPIResponse(t mockConstructorTestingTNewAPIResponse) *APIResponse {
	mock := &APIResponse{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
