apiVersion: v1
kind: Service
metadata:
  name: go-tmpl-backend
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
spec:
  selector:
    app: go-tmpl-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP